name: Update Private Repos Badge

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Compute repo counts
        id: counts
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_PAT || secrets.GH_TOKEN }}
          GH_USER: Kazu-K0032
        run: |
          set -euo pipefail
          echo "Fetching repo counts for $GH_USER"
          Q_PRIV='{"query":"query($login:String!){ user(login:$login){ repositories(privacy:PRIVATE,ownerAffiliations:OWNER){ totalCount } } }","variables":{"login":"'"$GH_USER"'"}}'
          Q_PUB='{"query":"query($login:String!){ user(login:$login){ repositories(privacy:PUBLIC,ownerAffiliations:OWNER){ totalCount } } }","variables":{"login":"'"$GH_USER"'"}}'
          PRIV=$(curl -s -H "Authorization: Bearer $GH_TOKEN" -H "Content-Type: application/json" -d "$Q_PRIV" https://api.github.com/graphql | jq -r '.data.user.repositories.totalCount // 0')
          PUB=$(curl -s -H "Authorization: Bearer $GH_TOKEN" -H "Content-Type: application/json" -d "$Q_PUB" https://api.github.com/graphql | jq -r '.data.user.repositories.totalCount // 0')
          TOTAL=$((PRIV + PUB))
          echo "private=$PRIV" >> "$GITHUB_OUTPUT"
          echo "public=$PUB" >> "$GITHUB_OUTPUT"
          echo "total=$TOTAL" >> "$GITHUB_OUTPUT"

      - name: Update badge JSONs
        run: |
          mkdir -p badge
          cat > badge/private-repos.json << JSON
          {
            "schemaVersion": 1,
            "label": "Private Repos",
            "message": "${{ steps.counts.outputs.private }}",
            "color": "blue"
          }
          JSON
          cat > badge/public-repos.json << JSON
          {
            "schemaVersion": 1,
            "label": "Public Repos",
            "message": "${{ steps.counts.outputs.public }}",
            "color": "informational"
          }
          JSON
          cat > badge/total-repos.json << JSON
          {
            "schemaVersion": 1,
            "label": "Total Repos",
            "message": "${{ steps.counts.outputs.total }}",
            "color": "success"
          }
          JSON

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git add badge/private-repos.json badge/public-repos.json badge/total-repos.json
          git commit -m "chore: update repo badges private=${{ steps.counts.outputs.private }} public=${{ steps.counts.outputs.public }} total=${{ steps.counts.outputs.total }}"
          git push
